version: '3.7'

services:
  taxi-server:
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    container_name: taxi-server
    depends_on:
      - taxi-redis
      - taxi-database
    env_file: 
      - ./.env.dev

    ports:
      - 8003:8000

  taxi-redis:
    container_name: taxi-redis
    image: redis:6-alpine

  taxi-database:
    container_name: taxi-database
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
    expose:
      - 5432
    volumes:
      - taxi-database:/var/lib/postgresql/data

volumes:
  taxi-database:

